spring.application.name=upload-file

# C?u hình cloudinary
cloudinary.cloud_name=dwqmfiprt
cloudinary.api_key=449161621123244
cloudinary.api_secret=EMle758_0h8CKEikND-W-6SPYKI

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB

#c?u hình g?i mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hung18061999hung@gmail.com
spring.mail.password=owyxkuxfizwylawb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

